# Devnet0 is a tiny devnet. Only a single validator, an archive node (for the relayer), and two anvils.
# This is aimed at local dev environments.

network = "devnet"
anvil_chains = ["mock_op", "mock_arb"]
ephemeral_genesis = "2_magellan"

[node.validator01]

[node.fullnode01]
mode="archive"
